//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpineHero.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Notifications : global::System.Configuration.ApplicationSettingsBase {
        
        private static Notifications defaultInstance = ((Notifications)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Notifications())));
        
        public static Notifications Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PopupNotification {
            get {
                return ((bool)(this["PopupNotification"]));
            }
            set {
                this["PopupNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint PopupNotificationTimeLimit {
            get {
                return ((uint)(this["PopupNotificationTimeLimit"]));
            }
            set {
                this["PopupNotificationTimeLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DimNotification {
            get {
                return ((bool)(this["DimNotification"]));
            }
            set {
                this["DimNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint DimNotificationTimeLimit {
            get {
                return ((uint)(this["DimNotificationTimeLimit"]));
            }
            set {
                this["DimNotificationTimeLimit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PopupNotificationDisplayInterval {
            get {
                return ((int)(this["PopupNotificationDisplayInterval"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PopupNotificationFadeOutMiliseconds {
            get {
                return ((int)(this["PopupNotificationFadeOutMiliseconds"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NotificationAreaNotification {
            get {
                return ((bool)(this["NotificationAreaNotification"]));
            }
            set {
                this["NotificationAreaNotification"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:10")]
        public global::System.TimeSpan DimNotificationFadeIn {
            get {
                return ((global::System.TimeSpan)(this["DimNotificationFadeIn"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00.5000000")]
        public global::System.TimeSpan DimNotificationFadeOut {
            get {
                return ((global::System.TimeSpan)(this["DimNotificationFadeOut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int UnknownPostureLimit {
            get {
                return ((int)(this["UnknownPostureLimit"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BreakNotification {
            get {
                return ((bool)(this["BreakNotification"]));
            }
            set {
                this["BreakNotification"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public uint BreakNotificationTimeLimit {
            get {
                return ((uint)(this["BreakNotificationTimeLimit"]));
            }
            set {
                this["BreakNotificationTimeLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:01:00")]
        public global::System.TimeSpan BreakNotificationBreakLength {
            get {
                return ((global::System.TimeSpan)(this["BreakNotificationBreakLength"]));
            }
            set {
                this["BreakNotificationBreakLength"] = value;
            }
        }
    }
}
