//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpineHero.Views.MainMenuItems {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpineHero.Views.MainMenuItems.Translation", typeof(Translation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to breaks.
        /// </summary>
        internal static string Breaks {
            get {
                return ResourceManager.GetString("Breaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longest time 
        ///of correct sitting.
        /// </summary>
        internal static string LongestTime {
            get {
                return ResourceManager.GetString("LongestTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of correct sitting.
        /// </summary>
        internal static string Of1 {
            get {
                return ResourceManager.GetString("Of1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (of.
        /// </summary>
        internal static string Of2 {
            get {
                return ResourceManager.GetString("Of2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hours totally).
        /// </summary>
        internal static string Of3 {
            get {
                return ResourceManager.GetString("Of3", resourceCulture);
            }
        }
    }
}
