//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpineHero.Views.DialogWindows {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpineHero.Views.DialogWindows.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine Hero couldn&apos;t recognize your face &amp;amp; posture. &amp;#xA; Check lighting conditions in your room..
        /// </summary>
        internal static string CheckLightMessage {
            get {
                return ResourceManager.GetString("CheckLightMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and click Set.
        /// </summary>
        internal static string ClickSet {
            get {
                return ResourceManager.GetString("ClickSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Settings tab. For comfort usage, we recommend interval around 5 minutes..
        /// </summary>
        internal static string Desc1 {
            get {
                return ResourceManager.GetString("Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New workplace? Wrong evaluation? Recalibrate to get the best results..
        /// </summary>
        internal static string Desc2 {
            get {
                return ResourceManager.GetString("Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine Hero will take care of your posture while running in the background - and you can focus on important things..
        /// </summary>
        internal static string Desc3 {
            get {
                return ResourceManager.GetString("Desc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please follow instructions in.
        /// </summary>
        internal static string FollowInstructions {
            get {
                return ResourceManager.GetString("FollowInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to sit correctly.
        /// </summary>
        internal static string HowToSit {
            get {
                return ResourceManager.GetString("HowToSit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://spinehero.com/blog/posts/how-to-sit-correctly.html.
        /// </summary>
        internal static string HowToSitBlogUrl {
            get {
                return ResourceManager.GetString("HowToSitBlogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pack://application:,,,/Resources/Images/HowToSitCorrectly.png.
        /// </summary>
        internal static string HowToSitImage {
            get {
                return ResourceManager.GetString("HowToSitImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spine Hero - How to sit correctly.
        /// </summary>
        internal static string HowToSitTitle {
            get {
                return ResourceManager.GetString("HowToSitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading camera....
        /// </summary>
        internal static string LoadingCamera {
            get {
                return ResourceManager.GetString("LoadingCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1. Adjust time limits for notifications.
        /// </summary>
        internal static string Point1 {
            get {
                return ResourceManager.GetString("Point1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2. Recalibrate in case of a problem.
        /// </summary>
        internal static string Point2 {
            get {
                return ResourceManager.GetString("Point2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3. Setup &amp;amp; forget.
        /// </summary>
        internal static string Point3 {
            get {
                return ResourceManager.GetString("Point3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 things you should know before:.
        /// </summary>
        internal static string Things {
            get {
                return ResourceManager.GetString("Things", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Spine Hero.
        /// </summary>
        internal static string WelcomeToSH {
            get {
                return ResourceManager.GetString("WelcomeToSH", resourceCulture);
            }
        }
    }
}
